name: EnvML
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10 # 3.12.1
  - plotly # 5.18.0
  - pip # 23.3.2
  - numpy # 1.26.3
  - pandas # 2.1.4
  - jupyter # 1.0.0
  - scipy # 1.11.4
  - matplotlib # 3.8.2
  - seaborn # 0.13.1
  - pip:
    - scikit-learn # 1.3.2
    - dash # 2.14.2
    - jupyter-dash # 0.4.2
    - graphviz # 0.20.1
    - pydotplus # 2.0.2