name: EnvML
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - plotly
  - pip
  - numpy
  - pandas
  - jupyter
  - scipy
  - matplotlib
  - seaborn
  - pip:
    - scikit-learn
    - dash
    - jupyter-dash
    - graphviz
    - pydotplus